import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";

import "./globals.css"
import type React from "react" 
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/auth-context";
import { SellerAuthProvider } from "@/context/authContextSeller";
import {  CartProvider } from "@/context/cartContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const pop = Poppins({
  weight: '400',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SweetHome",
  description: "Generated by Harshada Mali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pop.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > <Toaster position="top-right" richColors />
      <AuthProvider>
        <SellerAuthProvider>
          
      {children}
      
      </SellerAuthProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
